module.exports = {
  definitions: [
    { category: 'Home', title: 'View Dashboard', slug: 'view_dashboard', description: 'Permission to view the dashboard', sl_no: 1 },
    { category: 'Components', title: 'View Components', slug: 'view_components', description: 'Permission to view all components in the CMS', sl_no: 2 },
    { category: 'Components', title: 'Create Components', slug: 'create_components', description: 'Permission to create new components', sl_no: 3 },
    { category: 'Components', title: 'Edit Components', slug: 'edit_components', description: 'Permission to edit existing components', sl_no: 4 },
    { category: 'Components', title: 'Delete Components', slug: 'delete_components', description: 'Permission to delete components', sl_no: 5 },
    { category: 'Gallery', title: 'View Gallery', slug: 'view_gallery', description: 'Permission to view the gallery', sl_no: 6 },
    { category: 'Gallery', title: 'Upload Media to Gallery', slug: 'upload_media_to_gallery', description: 'Permission to upload media to the gallery', sl_no: 7 },
    { category: 'Menu Items', title: 'View Menu Items', slug: 'view_menu_items', description: 'Permission to view menu items', sl_no: 8 },
    { category: 'Menu Items', title: 'Create Menu Items', slug: 'create_menu_items', description: 'Permission to create new menu items', sl_no: 9 },
    { category: 'Menu Items', title: 'Edit Menu Items', slug: 'edit_menu_items', description: 'Permission to edit existing menu items', sl_no: 10 },
    { category: 'Menu Items', title: 'Delete Menu Items', slug: 'delete_menu_items', description: 'Permission to delete menu items', sl_no: 11 },
    { category: 'Menus', title: 'View Menus', slug: 'view_menus', description: 'Permission to view menus', sl_no: 12 },
    { category: 'Menus', title: 'Create Menus', slug: 'create_menus', description: 'Permission to create new menus', sl_no: 13 },
    { category: 'Menus', title: 'Edit Menus', slug: 'edit_menus', description: 'Permission to edit existing menus', sl_no: 14 },
    { category: 'Menus', title: 'Delete Menus', slug: 'delete_menus', description: 'Permission to delete menus', sl_no: 15 },
    { category: 'Navbars', title: 'View Navbars', slug: 'view_navbars', description: 'Permission to view navbars', sl_no: 16 },
    { category: 'Navbars', title: 'Create Navbars', slug: 'create_navbars', description: 'Permission to create new navbars', sl_no: 17 },
    { category: 'Navbars', title: 'Edit Navbars', slug: 'edit_navbars', description: 'Permission to edit existing navbars', sl_no: 18 },
    { category: 'Navbars', title: 'Delete Navbars', slug: 'delete_navbars', description: 'Permission to delete navbars', sl_no: 19 },
    { category: 'Sliders', title: 'View Sliders', slug: 'view_sliders', description: 'Permission to view sliders', sl_no: 20 },
    { category: 'Sliders', title: 'Create Sliders', slug: 'create_sliders', description: 'Permission to create new sliders', sl_no: 21 },
    { category: 'Sliders', title: 'Edit Sliders', slug: 'edit_sliders', description: 'Permission to edit existing sliders', sl_no: 22 },
    { category: 'Sliders', title: 'Delete Sliders', slug: 'delete_sliders', description: 'Permission to delete sliders', sl_no: 23 },
    { category: 'Forms', title: 'View Forms', slug: 'view_forms', description: 'Permission to view forms', sl_no: 24 },
    { category: 'Forms', title: 'Create Forms', slug: 'create_forms', description: 'Permission to create new forms', sl_no: 25 },
    { category: 'Forms', title: 'Edit Forms', slug: 'edit_forms', description: 'Permission to edit existing forms', sl_no: 26 },
    { category: 'Forms', title: 'Delete Forms', slug: 'delete_forms', description: 'Permission to delete forms', sl_no: 27 },
    { category: 'Footers', title: 'View Footers', slug: 'view_footers', description: 'Permission to view footers', sl_no: 28 },
    { category: 'Footers', title: 'Create Footers', slug: 'create_footers', description: 'Permission to create new footers', sl_no: 29 },
    { category: 'Footers', title: 'Edit Footers', slug: 'edit_footers', description: 'Permission to edit existing footers', sl_no: 30 },
    { category: 'Footers', title: 'Delete Footers', slug: 'delete_footers', description: 'Permission to delete footers', sl_no: 31 },
    { category: 'Form Responses', title: 'View Form Responses', slug: 'view_form_responses', description: 'Permission to view form responses', sl_no: 32 },
    { category: 'Creator Studio', title: 'View Pages', slug: 'view_pages', description: 'Permission to view pages', sl_no: 33 },
    { category: 'Creator Studio', title: 'Create Page', slug: 'create_page', description: 'Permission to create new pages', sl_no: 34 },
    { category: 'Creator Studio', title: 'Edit Pages', slug: 'edit_pages', description: 'Permission to edit existing pages', sl_no: 35 },
    { category: 'Creator Studio', title: 'Delete Pages', slug: 'delete_pages', description: 'Permission to delete pages', sl_no: 36 },
    { category: 'Tools', title: 'Access Doc to API', slug: 'access_doc_to_api', description: 'Permission to access Doc to API tool', sl_no: 46 },
    { category: 'Tools', title: 'Access Dynamic Form Builder', slug: 'access_dynamic_form_builder', description: 'Permission to access Dynamic Form Builder', sl_no: 47 },
    { category: 'Tools', title: 'Access Humanpal', slug: 'access_humanpal', description: 'Permission to access Humanpal tool', sl_no: 48 },
    { category: 'User Management', title: 'Create Users', slug: 'create_users', description: 'Permission to create new user accounts', sl_no: 49 },
    { category: 'User Management', title: 'Edit Users', slug: 'edit_users', description: 'Permission to edit existing user accounts', sl_no: 50 },
    { category: 'User Management', title: 'Delete Users', slug: 'delete_users', description: 'Permission to delete user accounts', sl_no: 51 },
    { category: 'User Management', title: 'View Users', slug: 'view_users', description: 'Permission to view user details', sl_no: 52 },
    { category: 'Role Management', title: 'Create Roles', slug: 'create_roles', description: 'Permission to create new roles', sl_no: 53 },
    { category: 'Role Management', title: 'Edit Roles', slug: 'edit_roles', description: 'Permission to edit existing roles', sl_no: 54 },
    { category: 'Role Management', title: 'Delete Roles', slug: 'delete_roles', description: 'Permission to delete roles', sl_no: 55 },
    { category: 'Role Management', title: 'Assign Roles', slug: 'assign_roles', description: 'Permission to assign roles to users', sl_no: 56 },
    { category: 'API Management', title: 'Access API', slug: 'access_api', description: 'Permission to access the CMS API', sl_no: 57 },
    { category: 'API Management', title: 'Create API Keys', slug: 'create_api_keys', description: 'Permission to create new API keys', sl_no: 58 },
    { category: 'API Management', title: 'Edit API Keys', slug: 'edit_api_keys', description: 'Permission to edit existing API keys', sl_no: 59 },
    { category: 'API Management', title: 'Delete API Keys', slug: 'delete_api_keys', description: 'Permission to delete API keys', sl_no: 60 },
    { category: 'API Management', title: 'View API Logs', slug: 'view_api_logs', description: 'Permission to view API access logs', sl_no: 61 },
    { category: 'Workflow Management', title: 'Create Workflows', slug: 'create_workflows', description: 'Permission to create new content workflows', sl_no: 62 },
    { category: 'Workflow Management', title: 'Edit Workflows', slug: 'edit_workflows', description: 'Permission to edit existing content workflows', sl_no: 63 },
    { category: 'Workflow Management', title: 'Delete Workflows', slug: 'delete_workflows', description: 'Permission to delete content workflows', sl_no: 64 },
    { category: 'Workflow Management', title: 'View Workflows', slug: 'view_workflows', description: 'Permission to view content workflows', sl_no: 65 },
    { category: 'Plugin Management', title: 'Install Plugins', slug: 'install_plugins', description: 'Permission to install new plugins', sl_no: 66 },
    { category: 'Plugin Management', title: 'Edit Plugins', slug: 'edit_plugins', description: 'Permission to configure installed plugins', sl_no: 67 },
    { category: 'Plugin Management', title: 'Delete Plugins', slug: 'delete_plugins', description: 'Permission to delete installed plugins', sl_no: 68 },
    { category: 'Plugin Management', title: 'View Plugins', slug: 'view_plugins', description: 'Permission to view installed plugins', sl_no: 69 },
    { category: 'System Management', title: 'Backup System', slug: 'backup_system', description: 'Permission to initiate a backup of the CMS', sl_no: 70 },
    { category: 'System Management', title: 'Restore System', slug: 'restore_system', description: 'Permission to restore the CMS from a backup', sl_no: 71 },
    { category: 'System Management', title: 'System Monitoring', slug: 'system_monitoring', description: 'Permission to view system performance and monitoring metrics', sl_no: 72 },
    { category: 'System Management', title: 'System Updates', slug: 'system_updates', description: 'Permission to initiate system updates', sl_no: 73 },
    { category: 'Audit Management', title: 'View Audit Logs', slug: 'view_audit_logs', description: 'Permission to view audit logs for user activities', sl_no: 74 },
    { category: 'Audit Management', title: 'Export Audit Logs', slug: 'export_audit_logs', description: 'Permission to export audit logs', sl_no: 75 },
    { category: 'Organization Management', title: 'Manage Organizations', slug: 'manage_organizations', description: 'Permission to create and manage organizations', sl_no: 76 },
    { category: 'Organization Management', title: 'View Organizations', slug: 'view_organizations', description: 'Permission to view organizations', sl_no: 77 },
    { category: 'Everything', title: 'Infinity', slug: 'admin_all', description: 'Power of all permissions', sl_no: 99 },
  ],

  roles: {
    'Super Admin': {
      description: 'Full access to all CMS features and settings',
      permission_slugs: ['admin_all'],
    },
    Admin: {
      description: 'Manage content, users, and roles without system-level access',
      permission_slugs: 'all_except_system',
    },
    Editor: {
      description: 'Create and edit content without user or role management',
      permission_slugs: 'editor',
    },
    Viewer: {
      description: 'Read-only access to CMS content',
      permission_slugs: 'viewer',
    },
  },

  route_map: {
    'GET:admin/users': 'view_users',
    'POST:admin/user': 'create_users',
    'PUT:admin/user/*': 'edit_users',
    'DELETE:admin/user/*': 'delete_users',
    'GET:roles': 'view_users',
    'POST:roles': 'create_roles',
    'PUT:roles/*': 'edit_roles',
    'DELETE:roles/*': 'delete_roles',
    'GET:permissions': 'view_users',
    'POST:permissions': 'create_roles',
    'PUT:permissions/*': 'edit_roles',
    'DELETE:permissions/*': 'delete_roles',
    'GET:pages': 'view_pages',
    'GET:pages/*/revisions': 'view_pages',
    'POST:pages/*/revisions/*/restore': 'edit_pages',
    'GET:pages/*': 'view_pages',
    'POST:pages': 'create_page',
    'PUT:pages/*': 'edit_pages',
    'DELETE:pages/*': 'delete_pages',
    'GET:form-submission': 'view_form_responses',
    'PUT:form-submission/*': 'edit_forms',
    'DELETE:form-submission/*': 'delete_forms',
    'POST:organizations/*/regenerate-site-key': 'manage_organizations',
    'GET:media': 'view_gallery',
    'POST:media/upload': 'upload_media_to_gallery',
    'PUT:media/*': 'edit_components',
    'DELETE:media/*': 'delete_components',
    'GET:menuitems': 'view_menu_items',
    'POST:menuitems': 'create_menu_items',
    'PUT:menuitems/*': 'edit_menu_items',
    'DELETE:menuitems/*': 'delete_menu_items',
    'GET:menus': 'view_menus',
    'POST:menus': 'create_menus',
    'PUT:menus/*': 'edit_menus',
    'DELETE:menus/*': 'delete_menus',
    'GET:navbars': 'view_navbars',
    'POST:navbars': 'create_navbars',
    'PUT:navbars/*': 'edit_navbars',
    'DELETE:navbars/*': 'delete_navbars',
    'GET:sliders': 'view_sliders',
    'POST:sliders': 'create_sliders',
    'PUT:sliders/*': 'edit_sliders',
    'DELETE:sliders/*': 'delete_sliders',
    'GET:cards': 'view_components',
    'POST:cards': 'create_components',
    'PUT:cards/*': 'edit_components',
    'DELETE:cards/*': 'delete_components',
    'GET:tables': 'view_components',
    'POST:tables': 'create_components',
    'PUT:tables/*': 'edit_components',
    'DELETE:tables/*': 'delete_components',
    'GET:product-types': 'view_components',
    'GET:product-types/*': 'view_components',
    'POST:product-types': 'create_components',
    'PUT:product-types/*': 'edit_components',
    'DELETE:product-types/*': 'delete_components',
    'GET:products': 'view_components',
    'GET:products/*': 'view_components',
    'POST:products': 'create_components',
    'PUT:products/*': 'edit_components',
    'DELETE:products/*': 'delete_components',
    'GET:footers': 'view_footers',
    'POST:footers': 'create_footers',
    'PUT:footers/*': 'edit_footers',
    'DELETE:footers/*': 'delete_footers',
    'GET:form_builder': 'view_forms',
    'POST:form_builder': 'create_forms',
    'PUT:form_builder/*': 'edit_forms',
    'DELETE:form_builder/*': 'delete_forms',
    'GET:formdata': 'view_form_responses',
    'PUT:formdata/*': 'edit_forms',
    'GET:organizations': 'manage_organizations',
    'POST:organizations': 'manage_organizations',
    'GET:organizations/*': 'manage_organizations',
    'PUT:organizations/*': 'manage_organizations',
    'DELETE:organizations/*': 'manage_organizations',
    'GET:organizations/*/roles': 'manage_organizations',
    'POST:organizations/*/roles': 'manage_organizations',
    'PUT:organizations/*/roles/*': 'manage_organizations',
    'DELETE:organizations/*/roles/*': 'manage_organizations',
    'GET:organizations/*/users': 'manage_organizations',
    'POST:organizations/*/users': 'manage_organizations',
    'PUT:organizations/*/users/*': 'manage_organizations',
    'DELETE:organizations/*/users/*': 'manage_organizations',
    'GET:dynamic': 'access_doc_to_api',
    'GET:dynamic/*': 'access_doc_to_api',
    'POST:dynamic': 'access_doc_to_api',
    'PUT:dynamic/*': 'access_doc_to_api',
    'DELETE:dynamic/*': 'access_doc_to_api',
    'GET:api-keys': 'create_api_keys',
    'GET:api-keys/*': 'create_api_keys',
    'POST:api-keys': 'create_api_keys',
    'PUT:api-keys/*': 'edit_api_keys',
    'DELETE:api-keys/*': 'delete_api_keys',
    'POST:diy-cms': 'access_doc_to_api',
    'GET:generated-models': 'access_doc_to_api',
    'PUT:generated-models/*': 'access_doc_to_api',
    'DELETE:generated-models/*': 'access_doc_to_api',
  },

  editorSlugs: [
    'view_dashboard', 'view_components', 'create_components', 'edit_components',
    'view_gallery', 'upload_media_to_gallery', 'view_menu_items', 'create_menu_items',
    'edit_menu_items', 'view_menus', 'create_menus', 'edit_menus', 'view_navbars',
    'create_navbars', 'edit_navbars', 'view_sliders', 'create_sliders', 'edit_sliders',
    'view_forms', 'create_forms', 'edit_forms', 'view_footers', 'create_footers',
    'edit_footers', 'view_form_responses', 'view_pages', 'create_page', 'edit_pages',
    'access_doc_to_api', 'access_dynamic_form_builder',
  ],

  viewerSlugs: [
    'view_dashboard', 'view_components', 'view_gallery', 'view_menu_items', 'view_menus',
    'view_navbars', 'view_sliders', 'view_forms', 'view_footers', 'view_form_responses',
    'view_pages',
  ],

  systemSlugs: [
    'backup_system', 'restore_system', 'system_monitoring', 'system_updates',
    'view_audit_logs', 'export_audit_logs', 'manage_organizations', 'view_organizations',
    'install_plugins', 'edit_plugins', 'delete_plugins', 'view_plugins',
  ],
};
