export const componentOptions = [
  {
    type: "title",
    name: "Title",
    icon: "/icons/headless/font.svg",
    premium: false,
    category: "Basic",
    description: "Add a heading or title to your page",
    tags: ["text", "heading"],
  },
  {
    type: "description",
    name: "Paragraph",
    icon: "/icons/headless/paragraph.svg",
    premium: false,
    category: "Basic",
    description: "Add text content to your page",
    tags: ["text", "content"],
  },
  {
    type: "titledescription",
    name: "Title & Desc.",
    icon: "/icons/headless/textdescription.svg",
    premium: false,
    category: "Basic",
    description: "Add a title with description",
    tags: ["text", "heading", "content"],
  },
  {
    type: "media",
    name: "Media",
    icon: "/icons/headless/media.svg",
    premium: false,
    category: "Media",
    description: "Add images or media content",
    tags: ["image", "media", "visual"],
  },
  {
    type: "menuitem",
    name: "Menu Item",
    icon: "/icons/headless/menuitems.svg",
    premium: false,
    category: "Layout",
    description: "Add one or more menu item links",
    tags: ["navigation", "menu", "link", "layout"],
  },
  {
    type: "navbar",
    name: "Navbar",
    icon: "/icons/headless/navbar.svg",
    premium: false,
    category: "Layout",
    description: "Add navigation bar",
    tags: ["navigation", "header", "layout"],
  },
  {
    type: "slider",
    name: "Slider",
    icon: "/icons/headless/slider.svg",
    premium: false,
    category: "Media",
    description: "Add image or content slider",
    tags: ["slider", "carousel", "media"],
  },
  {
    type: "footer",
    name: "Footer",
    icon: "/icons/headless/footer.svg",
    premium: false,
    category: "Layout",
    description: "Add footer section",
    tags: ["footer", "layout", "bottom"],
  },
  {
    type: "card",
    name: "Card",
    icon: "/icons/headless/cards.svg",
    premium: false,
    category: "Layout",
    description: "Add card component",
    tags: ["card", "layout", "container"],
  },
  {
    type: "video",
    name: "Video",
    icon: "/icons/headless/video.svg",
    premium: true,
    category: "Media",
    description: "Add video content",
    tags: ["video", "media", "player"],
  },
  {
    type: "table",
    name: "Table",
    icon: "/icons/headless/table.svg",
    premium: true,
    category: "Layout",
    description: "Add data table",
    tags: ["table", "data", "grid"],
  },
  {
    type: "accordion",
    name: "Accordion",
    icon: "/icons/headless/accordion.svg",
    premium: true,
    category: "Interactive",
    description: "Add collapsible content",
    tags: ["accordion", "collapse", "interactive"],
  },
  {
    type: "button",
    name: "Button",
    icon: "/icons/headless/button.svg",
    premium: true,
    category: "Interactive",
    description: "Add clickable button",
    tags: ["button", "click", "action"],
  },
  {
    type: "gallery",
    name: "Gallery",
    icon: "/icons/headless/gallery.svg",
    premium: true,
    category: "Media",
    description: "Add image gallery",
    tags: ["gallery", "images", "media"],
  },
  {
    type: "google-map",
    name: "Google Map",
    icon: "/icons/headless/map.svg",
    premium: true,
    category: "Interactive",
    description: "Add Google Maps integration",
    tags: ["map", "location", "interactive"],
  },
  {
    type: "iconlist",
    name: "Icon List",
    icon: "/icons/headless/iconlist.svg",
    premium: true,
    category: "Layout",
    description: "Add list with icons",
    tags: ["list", "icons", "layout"],
  },
  {
    type: "testimonial",
    name: "Testimonial",
    icon: "/icons/headless/testimonial.svg",
    premium: true,
    category: "Layout",
    description: "Add customer testimonials",
    tags: ["testimonial", "review", "quote"],
  },
  {
    type: "form",
    name: "Form",
    icon: "/icons/headless/exam.svg",
    premium: true,
    category: "Interactive",
    description: "Add input form",
    tags: ["form", "input", "interactive"],
  },
  {
    type: "infobox",
    name: "Info Box",
    icon: "/icons/headless/infobox.svg",
    premium: true,
    category: "Layout",
    description: "Add information box with media and details",
    tags: ["info", "media", "layout", "details"],
  },
];

export const categories = [
  { id: "all", name: "All", icon: "📦" },
  { id: "basic", name: "Basic", icon: "📝" },
  { id: "layout", name: "Layout", icon: "📐" },
  { id: "media", name: "Media", icon: "🎥" },
  { id: "interactive", name: "Interactive", icon: "🔄" },
  { id: "premium", name: "Premium", icon: "⭐" },
];
