import express from 'express';
import roleRoutes from './role.routes';
import permissionRoutes from './permission.routes';
import organizationRoutes from './organization.routes';
import navbarRoutes from './navbar.routes';
import menuItemRoutes from './menuItem.routes';
import footerRoutes from './footer.routes';
import sliderRoutes from './slider.routes';
import cardRoutes from './card.routes';
import tableRoutes from './table.routes';
import productTypeRoutes from './productType.routes';
import productRoutes from './product.routes';
import mediaRoutes from './media.routes';
import formBuilderRoutes from './formBuilder.routes';
import pageRoutes from './page.routes';
import formSubmissionRoutes from './formSubmission.routes';
import generatedModelRoutes from './generatedModel.routes';
import trashRoutes from './trash.routes';
import dynamicRoutes from './dynamic.routes';

const router = express.Router();

router.use(roleRoutes);
router.use(permissionRoutes);
router.use(organizationRoutes);
router.use(navbarRoutes);
router.use(menuItemRoutes);
router.use(footerRoutes);
router.use(sliderRoutes);
router.use(cardRoutes);
router.use(tableRoutes);
router.use(productTypeRoutes);
router.use(productRoutes);
router.use(mediaRoutes);
router.use(formBuilderRoutes);
router.use(pageRoutes);
router.use(formSubmissionRoutes);
router.use(generatedModelRoutes);
router.use(trashRoutes);
router.use(dynamicRoutes);

export default router;
