import {
  EditOutlined,
  MailOutlined,
  NumberOutlined,
  CalendarOutlined,
  SwapOutlined,
  AlignLeftOutlined,
  LinkOutlined,
  PictureOutlined,
  PhoneOutlined,
  CheckSquareOutlined,
  CheckCircleOutlined,
  TagsOutlined,
  DollarOutlined,
  FileTextOutlined,
  UploadOutlined,
  AppstoreOutlined,
  BgColorsOutlined,
  SlidersOutlined,
  EnvironmentOutlined,
  StarOutlined,
  BarcodeOutlined,
  DatabaseOutlined,
  ControlOutlined,
} from "@ant-design/icons";

export const PRODUCT_FIELD_PALETTE = [
  {
    field_type: "text",
    label: "Text Input",
    icon: <EditOutlined />,
    placeholder: "Enter text",
  },
  {
    field_type: "email",
    label: "Email",
    icon: <MailOutlined />,
    placeholder: "Enter email",
  },
  {
    field_type: "number",
    label: "Number",
    icon: <NumberOutlined />,
    placeholder: "Enter a number",
  },
  {
    field_type: "phone",
    label: "Phone",
    icon: <PhoneOutlined />,
    placeholder: "Enter phone number",
  },
  {
    field_type: "date",
    label: "Date",
    icon: <CalendarOutlined />,
    placeholder: "Select a date",
  },
  {
    field_type: "url",
    label: "URL",
    icon: <LinkOutlined />,
    placeholder: "https://",
  },
  {
    field_type: "select",
    label: "Select",
    icon: <SwapOutlined />,
    placeholder: "Select an option",
    options: [
      { label: "Option 1", value: "option_1" },
      { label: "Option 2", value: "option_2" },
    ],
  },
  {
    field_type: "textarea",
    label: "Textarea",
    icon: <AlignLeftOutlined />,
    placeholder: "Enter details",
  },
  {
    field_type: "media",
    label: "Media",
    icon: <PictureOutlined />,
    placeholder: "Select media",
  },
  {
    field_type: "checkbox",
    label: "Checkbox",
    icon: <CheckSquareOutlined />,
    placeholder: "Yes / No",
  },
  {
    field_type: "radio",
    label: "Radio",
    icon: <CheckCircleOutlined />,
    placeholder: "Choose one",
    options: [
      { label: "New", value: "new" },
      { label: "Used", value: "used" },
    ],
  },
  {
    field_type: "multiselect",
    label: "Multi Select",
    icon: <TagsOutlined />,
    placeholder: "Select options",
    options: [
      { label: "Tag 1", value: "tag_1" },
      { label: "Tag 2", value: "tag_2" },
      { label: "Tag 3", value: "tag_3" },
    ],
  },
  {
    field_type: "price",
    label: "Price",
    icon: <DollarOutlined />,
    placeholder: "0.00",
    currency: "BDT",
  },
  {
    field_type: "richtext",
    label: "Rich Text",
    icon: <FileTextOutlined />,
    placeholder: "Write description",
  },
  {
    field_type: "file",
    label: "File Upload",
    icon: <UploadOutlined />,
    placeholder: "Upload file",
  },
  {
    field_type: "gallery",
    label: "Gallery",
    icon: <AppstoreOutlined />,
    placeholder: "Select images",
  },
  {
    field_type: "color",
    label: "Color Picker",
    icon: <BgColorsOutlined />,
    placeholder: "#000000",
  },
  {
    field_type: "range",
    label: "Range / Slider",
    icon: <SlidersOutlined />,
    placeholder: "Select value",
    min: 0,
    max: 100,
    step: 1,
  },
  {
    field_type: "location",
    label: "Location",
    icon: <EnvironmentOutlined />,
    division_label: "Select Division",
    district_label: "Select District",
  },
  {
    field_type: "rating",
    label: "Rating",
    icon: <StarOutlined />,
    max_rating: 5,
  },
  {
    field_type: "sku",
    label: "SKU / Barcode",
    icon: <BarcodeOutlined />,
    placeholder: "Enter SKU",
  },
  {
    field_type: "quantity",
    label: "Quantity / Stock",
    icon: <DatabaseOutlined />,
    placeholder: "0",
    min: 0,
    max: 9999,
    step: 1,
  },
  {
    field_type: "toggle",
    label: "Toggle Switch",
    icon: <ControlOutlined />,
    placeholder: "On / Off",
  },
];
