ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS remember_token VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS permission_id JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS license_key VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_license_active BOOLEAN;

ALTER TABLE permissions ADD COLUMN IF NOT EXISTS api_request_type VARCHAR(255);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS api_endpoint VARCHAR(255);
