DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS footers;
DROP TABLE IF EXISTS sliders;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS navbars;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS media;
